#!/usr/bin/env python3
"""
KK&G DevOps Cybersecurity Engine - Plugin Architecture
======================================================
Enterprise-grade modular security framework with dynamic plugin loading,
hot-swappable modules, dependency management, and runtime isolation.
"""

import abc
import importlib
import importlib.util
import threading
import queue
import time
import hashlib
import json
import os
import sys
import traceback
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional, Callable, Type, Set, Union
from dataclasses import dataclass, field
from enum import Enum, auto
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import weakref
import inspect
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
import base64

# ============================================================================
# CORE PLUGIN FRAMEWORK TYPES & INTERFACES
# ============================================================================

class PluginState(Enum):
    """Plugin lifecycle states"""
    UNKNOWN = auto()
    DISCOVERED = auto()
    LOADED = auto()
    INITIALIZED = auto()
    ACTIVE = auto()
    SUSPENDED = auto()
    ERROR = auto()
    UNLOADING = auto()
    UNLOADED = auto()

class SecurityEventType(Enum):
    """Types of security events the system processes"""
    NETWORK_ANOMALY = "network_anomaly"
    ENDPOINT_THREAT = "endpoint_threat"
    USER_BEHAVIOR = "user_behavior"
    SYSTEM_EVENT = "system_event"
    THREAT_INTEL = "threat_intel"
    COMPLIANCE_VIOLATION = "compliance_violation"
    CUSTOM = "custom"

class ResponseActionType(Enum):
    """Types of response actions plugins can trigger"""
    BLOCK = "block"
    ALERT = "alert"
    QUARANTINE = "quarantine"
    LOG = "log"
    NOTIFY = "notify"
    CUSTOM = "custom"

@dataclass
class SecurityEvent:
    """Immutable security event passed to plugins"""
    event_id: str
    timestamp: datetime
    event_type: SecurityEventType
    source: str
    data: Dict[str, Any]
    severity: int  # 0-10 scale
    tags: Set[str] = field(default_factory=set)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Ensure immutability"""
        self.data = dict(self.data)  # Create copy
        self.tags = set(self.tags)   # Create copy
        self.metadata = dict(self.metadata)

@dataclass
class ResponseAction:
    """Response action generated by plugins"""
    action_id: str
    action_type: ResponseActionType
    priority: int  # 0-10 priority scale
    target: str
    parameters: Dict[str, Any]
    timeout: Optional[int] = None
    rollback_function: Optional[Callable] = None
    requires_approval: bool = False
    
class PluginCapability(Enum):
    """Capabilities that plugins can declare"""
    EVENT_PROCESSING = "event_processing"
    THREAT_DETECTION = "threat_detection"
    RESPONSE_GENERATION = "response_generation"
    DATA_ENRICHMENT = "data_enrichment"
    REPORTING = "reporting"
    INTEGRATION = "integration"

@dataclass
class PluginManifest:
    """Plugin metadata and requirements"""
    name: str
    version: str
    author: str
    description: str
    capabilities: List[PluginCapability]
    dependencies: List[str] = field(default_factory=list)
    platform_requirements: List[str] = field(default_factory=list)
    event_types: List[SecurityEventType] = field(default_factory=list)
    api_version: str = "1.0"
    license_required: bool = True
    config_schema: Dict[str, Any] = field(default_factory=dict)
    resource_limits: Dict[str, Any] = field(default_factory=dict)

# ============================================================================
# ABSTRACT BASE CLASSES FOR PLUGINS
# ============================================================================

class SecurityPlugin(abc.ABC):
    """
    Base class for all security plugins in the KK&G framework.
    Provides lifecycle management, event processing, and resource management.
    """
    
    def __init__(self):
        self._state = PluginState.UNKNOWN
        self._config: Dict[str, Any] = {}
        self._metrics: Dict[str, Any] = {}
        self._logger = None
        self._event_handlers: Dict[SecurityEventType, Callable] = {}
        self._lock = threading.RLock()
        
    @property
    @abc.abstractmethod
    def manifest(self) -> PluginManifest:
        """Plugin manifest defining capabilities and requirements"""
        pass
    
    @abc.abstractmethod
    def initialize(self, config: Dict[str, Any], logger) -> bool:
        """
        Initialize the plugin with configuration.
        Called once when plugin is loaded.
        
        Args:
            config: Plugin-specific configuration dictionary
            logger: Framework logger instance
            
        Returns:
            True if initialization successful, False otherwise
        """
        pass
    
    @abc.abstractmethod
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        """
        Process a security event and return response actions.
        
        Args:
            event: Security event to process
            
        Returns:
            List of response actions to execute
        """
        pass
    
    def get_health_status(self) -> Dict[str, Any]:
        """
        Return current plugin health and metrics.
        Override for custom health checks.
        """
        return {
            "state": self._state.name,
            "last_activity": datetime.now().isoformat(),
            "metrics": self._metrics.copy(),
            "config_valid": bool(self._config),
            "memory_usage": self._get_memory_usage()
        }
    
    def get_configuration_schema(self) -> Dict[str, Any]:
        """Return JSON schema for plugin configuration"""
        return self.manifest.config_schema
    
    def validate_configuration(self, config: Dict[str, Any]) -> bool:
        """Validate configuration against schema"""
        # Basic validation - can be extended with jsonschema
        required_fields = self.manifest.config_schema.get("required", [])
        return all(field in config for field in required_fields)
    
    def shutdown(self):
        """Cleanup when plugin is being unloaded"""
        with self._lock:
            self._state = PluginState.UNLOADING
            # Override in subclasses for custom cleanup
    
    def _get_memory_usage(self) -> int:
        """Get approximate memory usage in bytes"""
        try:
            import psutil
            import os
            process = psutil.Process(os.getpid())
            return process.memory_info().rss
        except ImportError:
            return 0
    
    # Internal framework methods - do not override
    def _set_state(self, state: PluginState):
        """Internal: Set plugin state"""
        with self._lock:
            self._state = state
    
    def _get_state(self) -> PluginState:
        """Internal: Get current plugin state"""
        return self._state
    
    def _set_config(self, config: Dict[str, Any]):
        """Internal: Set plugin configuration"""
        self._config = config.copy()

class EventProcessorPlugin(SecurityPlugin):
    """Specialized plugin for event processing"""
    
    def register_event_handler(self, event_type: SecurityEventType, 
                             handler: Callable[[SecurityEvent], List[ResponseAction]]):
        """Register a handler for specific event types"""
        self._event_handlers[event_type] = handler
    
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        """Route event to appropriate handler"""
        handler = self._event_handlers.get(event.event_type)
        if handler:
            return handler(event)
        return []

class ThreatDetectionPlugin(SecurityPlugin):
    """Specialized plugin for threat detection"""
    
    @abc.abstractmethod
    def detect_threats(self, event: SecurityEvent) -> List[Dict[str, Any]]:
        """
        Detect threats in the given event.
        
        Returns:
            List of threat indicators with confidence scores
        """
        pass
    
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        """Default implementation that converts threats to alerts"""
        threats = self.detect_threats(event)
        actions = []
        
        for threat in threats:
            action = ResponseAction(
                action_id=f"threat_alert_{threat.get('id', 'unknown')}",
                action_type=ResponseActionType.ALERT,
                priority=threat.get('confidence', 5),
                target=event.source,
                parameters={
                    "threat_type": threat.get('type'),
                    "confidence": threat.get('confidence'),
                    "details": threat.get('details', {})
                }
            )
            actions.append(action)
        
        return actions

class IntegrationPlugin(SecurityPlugin):
    """Specialized plugin for external integrations"""
    
    @abc.abstractmethod
    def connect(self) -> bool:
        """Establish connection to external system"""
        pass
    
    @abc.abstractmethod
    def disconnect(self):
        """Close connection to external system"""
        pass
    
    @abc.abstractmethod
    def send_data(self, data: Dict[str, Any]) -> bool:
        """Send data to external system"""
        pass

# ============================================================================
# PLUGIN DISCOVERY & LOADING SYSTEM
# ============================================================================

class PluginEncryption:
    """Handles encryption/decryption of plugin modules for IP protection"""
    
    def __init__(self, master_key: bytes):
        self.fernet = Fernet(master_key)
    
    @classmethod
    def generate_key(cls, password: str, salt: bytes = None) -> bytes:
        """Generate encryption key from password"""
        if salt is None:
            salt = os.urandom(16)
        
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100000,
        )
        key = base64.urlsafe_b64encode(kdf.derive(password.encode()))
        return key
    
    def encrypt_plugin(self, source_code: str) -> bytes:
        """Encrypt plugin source code"""
        return self.fernet.encrypt(source_code.encode())
    
    def decrypt_plugin(self, encrypted_data: bytes) -> str:
        """Decrypt plugin source code"""
        return self.fernet.decrypt(encrypted_data).decode()

@dataclass
class PluginDescriptor:
    """Internal descriptor for discovered plugins"""
    name: str
    path: Path
    manifest: PluginManifest
    encrypted: bool = False
    checksum: str = ""
    last_modified: datetime = field(default_factory=datetime.now)
    
class PluginDiscovery:
    """Discovers and catalogs available plugins"""
    
    def __init__(self, plugin_directories: List[Path], encryption: Optional[PluginEncryption] = None):
        self.plugin_directories = plugin_directories
        self.encryption = encryption
        self.discovered_plugins: Dict[str, PluginDescriptor] = {}
    
    def discover_plugins(self) -> Dict[str, PluginDescriptor]:
        """Discover all available plugins"""
        self.discovered_plugins.clear()
        
        for directory in self.plugin_directories:
            if not directory.exists():
                continue
            
            # Look for .py files and .kkg (encrypted) files
            for pattern in ["*.py", "*.kkg"]:
                for plugin_file in directory.glob(pattern):
                    try:
                        descriptor = self._analyze_plugin_file(plugin_file)
                        if descriptor:
                            self.discovered_plugins[descriptor.name] = descriptor
                    except Exception as e:
                        print(f"Error analyzing plugin {plugin_file}: {e}")
        
        return self.discovered_plugins
    
    def _analyze_plugin_file(self, plugin_path: Path) -> Optional[PluginDescriptor]:
        """Analyze a single plugin file"""
        try:
            encrypted = plugin_path.suffix == '.kkg'
            
            if encrypted:
                if not self.encryption:
                    return None
                
                # Decrypt and analyze
                with open(plugin_path, 'rb') as f:
                    encrypted_data = f.read()
                source_code = self.encryption.decrypt_plugin(encrypted_data)
            else:
                with open(plugin_path, 'r') as f:
                    source_code = f.read()
            
            # Extract manifest from source code
            manifest = self._extract_manifest(source_code, plugin_path.stem)
            
            if manifest:
                checksum = hashlib.sha256(source_code.encode()).hexdigest()
                last_modified = datetime.fromtimestamp(plugin_path.stat().st_mtime)
                
                return PluginDescriptor(
                    name=manifest.name,
                    path=plugin_path,
                    manifest=manifest,
                    encrypted=encrypted,
                    checksum=checksum,
                    last_modified=last_modified
                )
        
        except Exception as e:
            print(f"Failed to analyze plugin {plugin_path}: {e}")
            return None
    
    def _extract_manifest(self, source_code: str, default_name: str) -> Optional[PluginManifest]:
        """Extract plugin manifest from source code"""
        try:
            # Look for PLUGIN_MANIFEST constant
            namespace = {}
            exec(source_code, namespace)
            
            if 'PLUGIN_MANIFEST' in namespace:
                manifest_data = namespace['PLUGIN_MANIFEST']
                
                # Convert to PluginManifest object
                return PluginManifest(
                    name=manifest_data.get('name', default_name),
                    version=manifest_data.get('version', '1.0.0'),
                    author=manifest_data.get('author', 'Unknown'),
                    description=manifest_data.get('description', ''),
                    capabilities=[PluginCapability(c) for c in manifest_data.get('capabilities', [])],
                    dependencies=manifest_data.get('dependencies', []),
                    platform_requirements=manifest_data.get('platform_requirements', []),
                    event_types=[SecurityEventType(t) for t in manifest_data.get('event_types', [])],
                    api_version=manifest_data.get('api_version', '1.0'),
                    license_required=manifest_data.get('license_required', True),
                    config_schema=manifest_data.get('config_schema', {}),
                    resource_limits=manifest_data.get('resource_limits', {})
                )
        
        except Exception as e:
            print(f"Failed to extract manifest: {e}")
        
        return None

# ============================================================================
# PLUGIN LIFECYCLE MANAGER
# ============================================================================

class PluginManager:
    """
    Core plugin manager handling loading, lifecycle, dependency resolution,
    and runtime management of security plugins.
    """
    
    def __init__(self, 
                 plugin_directories: List[Path],
                 encryption_key: Optional[bytes] = None,
                 max_concurrent_plugins: int = 50):
        
        self.plugin_directories = plugin_directories
        self.encryption = PluginEncryption(encryption_key) if encryption_key else None
        self.max_concurrent_plugins = max_concurrent_plugins
        
        # Plugin management
        self.discovery = PluginDiscovery(plugin_directories, self.encryption)
        self.loaded_plugins: Dict[str, SecurityPlugin] = {}
        self.plugin_modules: Dict[str, Any] = {}  # Loaded Python modules
        self.plugin_configs: Dict[str, Dict[str, Any]] = {}
        self.plugin_dependencies: Dict[str, Set[str]] = {}
        
        # Runtime management
        self.event_queue = queue.Queue()
        self.response_queue = queue.Queue()
        self.executor = ThreadPoolExecutor(max_workers=max_concurrent_plugins)
        self.plugin_locks: Dict[str, threading.RLock] = {}
        
        # Metrics and monitoring
        self.plugin_metrics: Dict[str, Dict[str, Any]] = {}
        self.load_order: List[str] = []
        
        # Lifecycle callbacks
        self.lifecycle_callbacks: Dict[str, List[Callable]] = {
            'on_plugin_loaded': [],
            'on_plugin_unloaded': [],
            'on_plugin_error': []
        }
    
    def discover_plugins(self) -> Dict[str, PluginDescriptor]:
        """Discover all available plugins"""
        return self.discovery.discover_plugins()
    
    def load_plugin(self, plugin_name: str, config: Dict[str, Any] = None) -> bool:
        """
        Load and initialize a specific plugin.
        
        Args:
            plugin_name: Name of plugin to load
            config: Plugin-specific configuration
            
        Returns:
            True if loaded successfully, False otherwise
        """
        try:
            # Check if already loaded
            if plugin_name in self.loaded_plugins:
                return True
            
            # Discover if not already done
            if plugin_name not in self.discovery.discovered_plugins:
                self.discover_plugins()
            
            descriptor = self.discovery.discovered_plugins.get(plugin_name)
            if not descriptor:
                raise ValueError(f"Plugin '{plugin_name}' not found")
            
            # Validate dependencies
            if not self._validate_dependencies(descriptor):
                raise ValueError(f"Plugin '{plugin_name}' has unmet dependencies")
            
            # Load the plugin module
            plugin_module = self._load_plugin_module(descriptor)
            if not plugin_module:
                raise ValueError(f"Failed to load plugin module for '{plugin_name}'")
            
            # Instantiate plugin class
            plugin_instance = self._instantiate_plugin(plugin_module, descriptor)
            if not plugin_instance:
                raise ValueError(f"Failed to instantiate plugin '{plugin_name}'")
            
            # Initialize plugin
            final_config = config or self.plugin_configs.get(plugin_name, {})
            if not plugin_instance.validate_configuration(final_config):
                raise ValueError(f"Invalid configuration for plugin '{plugin_name}'")
            
            plugin_instance._set_config(final_config)
            
            if not plugin_instance.initialize(final_config, self._create_plugin_logger(plugin_name)):
                raise ValueError(f"Plugin '{plugin_name}' initialization failed")
            
            # Register plugin
            self.loaded_plugins[plugin_name] = plugin_instance
            self.plugin_modules[plugin_name] = plugin_module
            self.plugin_locks[plugin_name] = threading.RLock()
            self.load_order.append(plugin_name)
            
            plugin_instance._set_state(PluginState.ACTIVE)
            
            # Initialize metrics
            self.plugin_metrics[plugin_name] = {
                'load_time': datetime.now(),
                'events_processed': 0,
                'responses_generated': 0,
                'errors': 0,
                'last_activity': datetime.now()
            }
            
            # Notify callbacks
            for callback in self.lifecycle_callbacks['on_plugin_loaded']:
                try:
                    callback(plugin_name, plugin_instance)
                except Exception as e:
                    print(f"Lifecycle callback error: {e}")
            
            print(f"✅ Plugin '{plugin_name}' loaded successfully")
            return True
            
        except Exception as e:
            print(f"❌ Failed to load plugin '{plugin_name}': {e}")
            self._handle_plugin_error(plugin_name, e)
            return False
    
    def unload_plugin(self, plugin_name: str) -> bool:
        """Unload a specific plugin"""
        try:
            if plugin_name not in self.loaded_plugins:
                return True
            
            plugin = self.loaded_plugins[plugin_name]
            plugin._set_state(PluginState.UNLOADING)
            
            # Call shutdown
            plugin.shutdown()
            
            # Remove from active plugins
            del self.loaded_plugins[plugin_name]
            if plugin_name in self.plugin_modules:
                del self.plugin_modules[plugin_name]
            if plugin_name in self.plugin_locks:
                del self.plugin_locks[plugin_name]
            if plugin_name in self.load_order:
                self.load_order.remove(plugin_name)
            
            # Notify callbacks
            for callback in self.lifecycle_callbacks['on_plugin_unloaded']:
                try:
                    callback(plugin_name, plugin)
                except Exception as e:
                    print(f"Lifecycle callback error: {e}")
            
            print(f"✅ Plugin '{plugin_name}' unloaded successfully")
            return True
            
        except Exception as e:
            print(f"❌ Failed to unload plugin '{plugin_name}': {e}")
            return False
    
    def reload_plugin(self, plugin_name: str) -> bool:
        """Reload a plugin (unload then load)"""
        config = self.plugin_configs.get(plugin_name, {})
        
        if plugin_name in self.loaded_plugins:
            if not self.unload_plugin(plugin_name):
                return False
        
        return self.load_plugin(plugin_name, config)
    
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        """Process event through all relevant plugins"""
        responses = []
        
        for plugin_name, plugin in self.loaded_plugins.items():
            try:
                if plugin._get_state() != PluginState.ACTIVE:
                    continue
                
                # Check if plugin handles this event type
                if (event.event_type in plugin.manifest.event_types or 
                    not plugin.manifest.event_types):
                    
                    with self.plugin_locks[plugin_name]:
                        plugin_responses = plugin.process_event(event)
                        responses.extend(plugin_responses or [])
                        
                        # Update metrics
                        self.plugin_metrics[plugin_name]['events_processed'] += 1
                        self.plugin_metrics[plugin_name]['responses_generated'] += len(plugin_responses or [])
                        self.plugin_metrics[plugin_name]['last_activity'] = datetime.now()
                        
            except Exception as e:
                self._handle_plugin_error(plugin_name, e)
                self.plugin_metrics[plugin_name]['errors'] += 1
        
        return responses
    
    def get_plugin_status(self, plugin_name: str = None) -> Dict[str, Any]:
        """Get status of specific plugin or all plugins"""
        if plugin_name:
            if plugin_name in self.loaded_plugins:
                plugin = self.loaded_plugins[plugin_name]
                return {
                    'name': plugin_name,
                    'state': plugin._get_state().name,
                    'health': plugin.get_health_status(),
                    'metrics': self.plugin_metrics.get(plugin_name, {}),
                    'manifest': plugin.manifest.__dict__
                }
            else:
                return {'error': f'Plugin {plugin_name} not loaded'}
        
        # Return status for all plugins
        status = {}
        for name in self.loaded_plugins:
            status[name] = self.get_plugin_status(name)
        
        return status
    
    def set_plugin_config(self, plugin_name: str, config: Dict[str, Any]):
        """Set configuration for a plugin"""
        self.plugin_configs[plugin_name] = config
        
        # If plugin is loaded, reconfigure it
        if plugin_name in self.loaded_plugins:
            plugin = self.loaded_plugins[plugin_name]
            if plugin.validate_configuration(config):
                plugin._set_config(config)
                # Optionally trigger reconfiguration
    
    def add_lifecycle_callback(self, event: str, callback: Callable):
        """Add lifecycle event callback"""
        if event in self.lifecycle_callbacks:
            self.lifecycle_callbacks[event].append(callback)
    
    def get_loaded_plugins(self) -> List[str]:
        """Get list of loaded plugin names"""
        return list(self.loaded_plugins.keys())
    
    def get_available_plugins(self) -> List[str]:
        """Get list of available plugin names"""
        return list(self.discovery.discovered_plugins.keys())
    
    # Private methods
    
    def _validate_dependencies(self, descriptor: PluginDescriptor) -> bool:
        """Validate that plugin dependencies are met"""
        for dep in descriptor.manifest.dependencies:
            if dep not in self.loaded_plugins:
                # Try to load dependency
                if not self.load_plugin(dep):
                    return False
        return True
    
    def _load_plugin_module(self, descriptor: PluginDescriptor) -> Optional[Any]:
        """Load Python module for plugin"""
        try:
            if descriptor.encrypted and self.encryption:
                # Load encrypted plugin
                with open(descriptor.path, 'rb') as f:
                    encrypted_data = f.read()
                source_code = self.encryption.decrypt_plugin(encrypted_data)
                
                # Create module from source
                spec = importlib.util.spec_from_loader(descriptor.name, loader=None)
                module = importlib.util.module_from_spec(spec)
                exec(source_code, module.__dict__)
                
                return module
            else:
                # Load regular Python file
                spec = importlib.util.spec_from_file_location(descriptor.name, descriptor.path)
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                
                return module
                
        except Exception as e:
            print(f"Failed to load module for {descriptor.name}: {e}")
            return None
    
    def _instantiate_plugin(self, module: Any, descriptor: PluginDescriptor) -> Optional[SecurityPlugin]:
        """Find and instantiate plugin class from module"""
        try:
            # Look for classes that inherit from SecurityPlugin
            for name, obj in inspect.getmembers(module):
                if (inspect.isclass(obj) and 
                    issubclass(obj, SecurityPlugin) and 
                    obj != SecurityPlugin):
                    
                    return obj()
            
            return None
            
        except Exception as e:
            print(f"Failed to instantiate plugin from {descriptor.name}: {e}")
            return None
    
    def _create_plugin_logger(self, plugin_name: str):
        """Create logger instance for plugin"""
        # Return framework logger or create plugin-specific logger
        return None  # Placeholder - implement logging framework integration
    
    def _handle_plugin_error(self, plugin_name: str, error: Exception):
        """Handle plugin errors"""
        print(f"Plugin error in {plugin_name}: {error}")
        traceback.print_exc()
        
        # Notify error callbacks
        for callback in self.lifecycle_callbacks['on_plugin_error']:
            try:
                callback(plugin_name, error)
            except Exception as callback_error:
                print(f"Error callback failed: {callback_error}")
        
        # Consider suspending plugin if too many errors
        if plugin_name in self.plugin_metrics:
            error_count = self.plugin_metrics[plugin_name].get('errors', 0)
            if error_count > 10:  # Configurable threshold
                if plugin_name in self.loaded_plugins:
                    self.loaded_plugins[plugin_name]._set_state(PluginState.ERROR)

# ============================================================================
# EXAMPLE PLUGIN IMPLEMENTATIONS
# ============================================================================

# Example: Network Anomaly Detection Plugin
class NetworkAnomalyPlugin(ThreatDetectionPlugin):
    """Example plugin for network anomaly detection"""
    
    @property
    def manifest(self) -> PluginManifest:
        return PluginManifest(
            name="network_anomaly_detector",
            version="1.0.0",
            author="KK&G DevOps",
            description="Detects network anomalies using statistical analysis",
            capabilities=[PluginCapability.THREAT_DETECTION, PluginCapability.EVENT_PROCESSING],
            event_types=[SecurityEventType.NETWORK_ANOMALY],
            config_schema={
                "type": "object",
                "required": ["threshold", "window_size"],
                "properties": {
                    "threshold": {"type": "number", "minimum": 0, "maximum": 1},
                    "window_size": {"type": "integer", "minimum": 1}
                }
            }
        )
    
    def initialize(self, config: Dict[str, Any], logger) -> bool:
        self.threshold = config.get('threshold', 0.8)
        self.window_size = config.get('window_size', 100)
        self.baseline_data = []
        return True
    
    def detect_threats(self, event: SecurityEvent) -> List[Dict[str, Any]]:
        # Simplified anomaly detection logic
        if event.event_type != SecurityEventType.NETWORK_ANOMALY:
            return []
        
        # Analyze network metrics
        network_data = event.data.get('network_metrics', {})
        anomaly_score = self._calculate_anomaly_score(network_data)
        
        if anomaly_score > self.threshold:
            return [{
                'id': f"network_anomaly_{event.event_id}",
                'type': 'network_anomaly',
                'confidence': anomaly_score,
                'details': {
                    'anomaly_score': anomaly_score,
                    'threshold': self.threshold,
                    'metrics': network_data
                }
            }]
        
        return []
    
    def _calculate_anomaly_score(self, network_data: Dict[str, Any]) -> float:
        # Placeholder anomaly scoring logic
        # In real implementation, use statistical methods or ML
        baseline_avg = sum(self.baseline_data) / len(self.baseline_data) if self.baseline_data else 0
        current_value = network_data.get('bandwidth_usage', 0)
        
        if baseline_avg == 0:
            return 0.0
        
        deviation = abs(current_value - baseline_avg) / baseline_avg
        return min(deviation, 1.0)

# Example manifest constant for the plugin file
NETWORK_ANOMALY_PLUGIN_MANIFEST = {
    'name': 'network_anomaly_detector',
    'version': '1.0.0',
    'author': 'KK&G DevOps',
    'description': 'Detects network anomalies using statistical analysis',
    'capabilities': ['threat_detection', 'event_processing'],
    'event_types': ['network_anomaly'],
    'dependencies': [],
    'platform_requirements': [],
    'api_version': '1.0',
    'license_required': True,
    'config_schema': {
        'type': 'object',
        'required': ['threshold', 'window_size'],
        'properties': {
            'threshold': {'type': 'number', 'minimum': 0, 'maximum': 1},
            'window_size': {'type': 'integer', 'minimum': 1}
        }
    },
    'resource_limits': {
        'max_memory_mb': 100,
        'max_cpu_percent': 10
    }
}

# ============================================================================
# ADVANCED PLUGIN FEATURES
# ============================================================================

class PluginResourceMonitor:
    """Monitors and enforces resource limits for plugins"""
    
    def __init__(self, plugin_manager: PluginManager):
        self.plugin_manager = plugin_manager
        self.resource_usage: Dict[str, Dict[str, Any]] = {}
        self.monitoring_active = False
        self.monitor_thread = None
        
    def start_monitoring(self):
        """Start resource monitoring thread"""
        if not self.monitoring_active:
            self.monitoring_active = True
            self.monitor_thread = threading.Thread(target=self._monitor_resources, daemon=True)
            self.monitor_thread.start()
    
    def stop_monitoring(self):
        """Stop resource monitoring"""
        self.monitoring_active = False
        if self.monitor_thread:
            self.monitor_thread.join(timeout=5)
    
    def _monitor_resources(self):
        """Main monitoring loop"""
        import psutil
        
        while self.monitoring_active:
            try:
                for plugin_name, plugin in self.plugin_manager.loaded_plugins.items():
                    manifest = plugin.manifest
                    limits = manifest.resource_limits
                    
                    if not limits:
                        continue
                    
                    # Get current resource usage
                    current_usage = self._get_plugin_resource_usage(plugin_name)
                    self.resource_usage[plugin_name] = current_usage
                    
                    # Check limits
                    violations = []
                    
                    if 'max_memory_mb' in limits:
                        memory_mb = current_usage['memory_bytes'] / (1024 * 1024)
                        if memory_mb > limits['max_memory_mb']:
                            violations.append(f"Memory: {memory_mb:.1f}MB > {limits['max_memory_mb']}MB")
                    
                    if 'max_cpu_percent' in limits:
                        cpu_percent = current_usage['cpu_percent']
                        if cpu_percent > limits['max_cpu_percent']:
                            violations.append(f"CPU: {cpu_percent:.1f}% > {limits['max_cpu_percent']}%")
                    
                    if violations:
                        self._handle_resource_violation(plugin_name, violations)
                
                time.sleep(10)  # Check every 10 seconds
                
            except Exception as e:
                print(f"Resource monitoring error: {e}")
                time.sleep(5)
    
    def _get_plugin_resource_usage(self, plugin_name: str) -> Dict[str, Any]:
        """Get resource usage for a specific plugin"""
        try:
            import psutil
            process = psutil.Process()
            
            return {
                'memory_bytes': process.memory_info().rss,
                'cpu_percent': process.cpu_percent(),
                'threads': process.num_threads(),
                'open_files': len(process.open_files()),
                'timestamp': datetime.now()
            }
        except Exception:
            return {
                'memory_bytes': 0,
                'cpu_percent': 0,
                'threads': 0,
                'open_files': 0,
                'timestamp': datetime.now()
            }
    
    def _handle_resource_violation(self, plugin_name: str, violations: List[str]):
        """Handle resource limit violations"""
        print(f"⚠️ Resource violations for plugin '{plugin_name}': {', '.join(violations)}")
        
        # Suspend plugin if violations are severe
        if plugin_name in self.plugin_manager.loaded_plugins:
            plugin = self.plugin_manager.loaded_plugins[plugin_name]
            plugin._set_state(PluginState.SUSPENDED)
            
            # Log violation
            if plugin_name in self.plugin_manager.plugin_metrics:
                metrics = self.plugin_manager.plugin_metrics[plugin_name]
                metrics.setdefault('resource_violations', []).append({
                    'timestamp': datetime.now(),
                    'violations': violations
                })

class PluginHotReloader:
    """Handles hot reloading of plugins during development"""
    
    def __init__(self, plugin_manager: PluginManager):
        self.plugin_manager = plugin_manager
        self.file_watchers: Dict[str, Any] = {}
        self.watching = False
        
    def start_watching(self):
        """Start watching plugin files for changes"""
        try:
            import watchdog.observers
            import watchdog.events
            
            self.watching = True
            
            class PluginFileHandler(watchdog.events.FileSystemEventHandler):
                def __init__(self, hot_reloader):
                    self.hot_reloader = hot_reloader
                
                def on_modified(self, event):
                    if not event.is_directory and event.src_path.endswith(('.py', '.kkg')):
                        self.hot_reloader._handle_file_change(Path(event.src_path))
            
            observer = watchdog.observers.Observer()
            handler = PluginFileHandler(self)
            
            for directory in self.plugin_manager.plugin_directories:
                if directory.exists():
                    observer.schedule(handler, str(directory), recursive=False)
            
            observer.start()
            self.observer = observer
            
        except ImportError:
            print("⚠️ Watchdog not available - hot reloading disabled")
    
    def stop_watching(self):
        """Stop watching files"""
        self.watching = False
        if hasattr(self, 'observer'):
            self.observer.stop()
            self.observer.join()
    
    def _handle_file_change(self, file_path: Path):
        """Handle plugin file changes"""
        if not self.watching:
            return
        
        # Find which plugin this file belongs to
        for plugin_name, descriptor in self.plugin_manager.discovery.discovered_plugins.items():
            if descriptor.path == file_path:
                print(f"🔄 Plugin file changed: {plugin_name}")
                
                # Reload the plugin
                success = self.plugin_manager.reload_plugin(plugin_name)
                if success:
                    print(f"✅ Hot reloaded plugin: {plugin_name}")
                else:
                    print(f"❌ Failed to hot reload plugin: {plugin_name}")
                break

class PluginSandbox:
    """Provides sandboxed execution environment for plugins"""
    
    def __init__(self, plugin_name: str):
        self.plugin_name = plugin_name
        self.restricted_modules = {
            'os', 'sys', 'subprocess', 'importlib', 'eval', 'exec',
            'open', 'file', '__import__'
        }
        self.allowed_builtins = {
            'len', 'str', 'int', 'float', 'bool', 'list', 'dict',
            'set', 'tuple', 'range', 'enumerate', 'zip', 'map',
            'filter', 'sorted', 'reversed', 'sum', 'min', 'max'
        }
    
    def create_sandbox_globals(self) -> Dict[str, Any]:
        """Create restricted global namespace for plugin"""
        safe_builtins = {}
        import builtins
        
        for name in self.allowed_builtins:
            if hasattr(builtins, name):
                safe_builtins[name] = getattr(builtins, name)
        
        return {
            '__builtins__': safe_builtins,
            '__name__': f'plugin_{self.plugin_name}',
            'SecurityPlugin': SecurityPlugin,
            'SecurityEvent': SecurityEvent,
            'ResponseAction': ResponseAction,
            'PluginManifest': PluginManifest,
            'PluginCapability': PluginCapability,
            'SecurityEventType': SecurityEventType,
            'ResponseActionType': ResponseActionType,
            'datetime': datetime,
            'timedelta': timedelta,
        }
    
    def execute_in_sandbox(self, code: str, globals_dict: Dict[str, Any] = None):
        """Execute code in sandbox"""
        if globals_dict is None:
            globals_dict = self.create_sandbox_globals()
        
        try:
            exec(code, globals_dict)
            return globals_dict
        except Exception as e:
            raise SecurityError(f"Sandbox execution failed: {e}")

class SecurityError(Exception):
    """Custom exception for security-related plugin errors"""
    pass

class PluginRegistry:
    """Central registry for plugin metadata and discovery"""
    
    def __init__(self):
        self.registry: Dict[str, Dict[str, Any]] = {}
        self.categories: Dict[str, List[str]] = {}
        self.compatibility_matrix: Dict[str, List[str]] = {}
    
    def register_plugin(self, manifest: PluginManifest, metadata: Dict[str, Any] = None):
        """Register a plugin in the central registry"""
        self.registry[manifest.name] = {
            'manifest': manifest,
            'metadata': metadata or {},
            'registration_time': datetime.now(),
            'compatible_versions': [],
            'known_issues': [],
            'download_count': 0,
            'rating': 0.0,
            'reviews': []
        }
        
        # Categorize by capabilities
        for capability in manifest.capabilities:
            category = capability.value
            if category not in self.categories:
                self.categories[category] = []
            if manifest.name not in self.categories[category]:
                self.categories[category].append(manifest.name)
    
    def search_plugins(self, 
                      capability: PluginCapability = None,
                      event_type: SecurityEventType = None,
                      platform: str = None) -> List[str]:
        """Search for plugins by criteria"""
        results = []
        
        for plugin_name, info in self.registry.items():
            manifest = info['manifest']
            
            # Filter by capability
            if capability and capability not in manifest.capabilities:
                continue
            
            # Filter by event type
            if event_type and event_type not in manifest.event_types:
                continue
            
            # Filter by platform
            if platform and platform not in manifest.platform_requirements:
                continue
            
            results.append(plugin_name)
        
        return results
    
    def get_plugin_info(self, plugin_name: str) -> Dict[str, Any]:
        """Get detailed information about a plugin"""
        return self.registry.get(plugin_name, {})

class PluginMarketplace:
    """Plugin marketplace for discovering and installing new plugins"""
    
    def __init__(self, registry: PluginRegistry, encryption: PluginEncryption):
        self.registry = registry
        self.encryption = encryption
        self.marketplace_url = "https://plugins.kkgdevops.com"
        self.local_cache = Path("~/.kkg/plugin_cache").expanduser()
        self.local_cache.mkdir(parents=True, exist_ok=True)
    
    def search_marketplace(self, query: str) -> List[Dict[str, Any]]:
        """Search the online marketplace for plugins"""
        # Placeholder - would implement actual marketplace API calls
        return []
    
    def download_plugin(self, plugin_name: str, version: str = "latest") -> bool:
        """Download and install plugin from marketplace"""
        try:
            # Placeholder - implement actual download logic
            print(f"Downloading plugin {plugin_name} version {version}")
            
            # Would verify signatures, check compatibility, etc.
            
            return True
        except Exception as e:
            print(f"Failed to download plugin {plugin_name}: {e}")
            return False
    
    def verify_plugin_signature(self, plugin_path: Path) -> bool:
        """Verify digital signature of plugin"""
        # Implement cryptographic verification
        return True
    
    def check_for_updates(self, installed_plugins: List[str]) -> Dict[str, str]:
        """Check for plugin updates"""
        updates_available = {}
        
        # Placeholder - check marketplace for newer versions
        
        return updates_available

# ============================================================================
# ADVANCED PLUGIN EXAMPLES
# ============================================================================

class MLThreatDetectionPlugin(ThreatDetectionPlugin):
    """Advanced ML-based threat detection plugin"""
    
    @property
    def manifest(self) -> PluginManifest:
        return PluginManifest(
            name="ml_threat_detector",
            version="2.0.0",
            author="KK&G DevOps AI Team",
            description="Machine learning-based advanced threat detection",
            capabilities=[
                PluginCapability.THREAT_DETECTION,
                PluginCapability.DATA_ENRICHMENT,
                PluginCapability.EVENT_PROCESSING
            ],
            dependencies=["numpy", "scikit-learn", "tensorflow"],
            event_types=[
                SecurityEventType.NETWORK_ANOMALY,
                SecurityEventType.ENDPOINT_THREAT,
                SecurityEventType.USER_BEHAVIOR
            ],
            config_schema={
                "type": "object",
                "required": ["model_path", "confidence_threshold"],
                "properties": {
                    "model_path": {"type": "string"},
                    "confidence_threshold": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                    "batch_size": {"type": "integer", "minimum": 1, "maximum": 1000},
                    "update_frequency": {"type": "integer", "minimum": 3600}
                }
            },
            resource_limits={
                "max_memory_mb": 512,
                "max_cpu_percent": 30,
                "max_gpu_memory_mb": 1024
            }
        )
    
    def initialize(self, config: Dict[str, Any], logger) -> bool:
        self.model_path = config['model_path']
        self.confidence_threshold = config.get('confidence_threshold', 0.8)
        self.batch_size = config.get('batch_size', 32)
        self.update_frequency = config.get('update_frequency', 3600)
        
        # Initialize ML model (placeholder)
        self.model = self._load_model()
        self.feature_extractor = self._initialize_feature_extractor()
        
        # Training data buffer for continuous learning
        self.training_buffer = []
        self.last_update = datetime.now()
        
        return self.model is not None
    
    def detect_threats(self, event: SecurityEvent) -> List[Dict[str, Any]]:
        threats = []
        
        try:
            # Extract features from event
            features = self.feature_extractor.extract_features(event)
            
            # Run inference
            prediction = self.model.predict([features])[0]
            confidence = self.model.predict_proba([features])[0].max()
            
            if prediction == 1 and confidence >= self.confidence_threshold:
                threats.append({
                    'id': f"ml_threat_{event.event_id}",
                    'type': 'ml_detected_threat',
                    'confidence': confidence,
                    'details': {
                        'model_version': '2.0.0',
                        'features_used': len(features),
                        'prediction_confidence': confidence,
                        'threat_category': self._classify_threat_type(features)
                    }
                })
            
            # Add to training buffer for continuous learning
            self.training_buffer.append((features, event))
            if len(self.training_buffer) > 1000:
                self.training_buffer.pop(0)
            
            # Periodic model updates
            if (datetime.now() - self.last_update).seconds > self.update_frequency:
                self._update_model()
                self.last_update = datetime.now()
                
        except Exception as e:
            print(f"ML threat detection error: {e}")
        
        return threats
    
    def _load_model(self):
        """Load the ML model"""
        try:
            # Placeholder - load actual model
            from sklearn.ensemble import IsolationForest
            return IsolationForest(contamination=0.1, random_state=42)
        except ImportError:
            print("ML dependencies not available")
            return None
    
    def _initialize_feature_extractor(self):
        """Initialize feature extraction pipeline"""
        return FeatureExtractor()
    
    def _classify_threat_type(self, features) -> str:
        """Classify the type of detected threat"""
        # Simplified threat categorization
        if features[0] > 0.8:
            return "network_intrusion"
        elif features[1] > 0.7:
            return "malware_activity"
        else:
            return "anomalous_behavior"
    
    def _update_model(self):
        """Update model with new training data"""
        if len(self.training_buffer) < 100:
            return
        
        try:
            # Retrain model with new data (simplified)
            features = [item[0] for item in self.training_buffer]
            
            # In real implementation, would have labeled data
            # For now, use unsupervised learning
            self.model.fit(features)
            
            print(f"✅ ML model updated with {len(features)} samples")
            
        except Exception as e:
            print(f"Model update failed: {e}")

class FeatureExtractor:
    """Extracts features from security events for ML processing"""
    
    def extract_features(self, event: SecurityEvent) -> List[float]:
        """Extract numerical features from security event"""
        features = []
        
        # Time-based features
        features.append(event.timestamp.hour / 24.0)  # Hour normalized
        features.append(event.timestamp.weekday() / 7.0)  # Weekday normalized
        
        # Event metadata features
        features.append(event.severity / 10.0)  # Severity normalized
        features.append(len(event.tags))  # Number of tags
        
        # Data-based features (simplified)
        data_size = len(str(event.data))
        features.append(min(data_size / 1000.0, 1.0))  # Data size normalized
        
        # Source-based features
        source_entropy = self._calculate_entropy(event.source)
        features.append(source_entropy)
        
        # Pad to fixed size (e.g., 20 features)
        while len(features) < 20:
            features.append(0.0)
        
        return features[:20]  # Ensure consistent size
    
    def _calculate_entropy(self, text: str) -> float:
        """Calculate Shannon entropy of text"""
        import math
        if not text:
            return 0.0
        
        char_counts = {}
        for char in text:
            char_counts[char] = char_counts.get(char, 0) + 1
        
        entropy = 0.0
        text_len = len(text)
        
        for count in char_counts.values():
            probability = count / text_len
            if probability > 0:
                entropy -= probability * math.log2(probability)
        
        return entropy / 8.0  # Normalize to 0-1 range

class SIEMIntegrationPlugin(IntegrationPlugin):
    """Plugin for integrating with SIEM systems"""
    
    @property
    def manifest(self) -> PluginManifest:
        return PluginManifest(
            name="siem_integration",
            version="1.5.0",
            author="KK&G DevOps Integration Team",
            description="Bi-directional integration with SIEM platforms",
            capabilities=[
                PluginCapability.INTEGRATION,
                PluginCapability.REPORTING,
                PluginCapability.DATA_ENRICHMENT
            ],
            config_schema={
                "type": "object",
                "required": ["siem_type", "endpoint", "api_key"],
                "properties": {
                    "siem_type": {"type": "string", "enum": ["splunk", "qradar", "sentinel", "elastic"]},
                    "endpoint": {"type": "string", "format": "uri"},
                    "api_key": {"type": "string"},
                    "batch_size": {"type": "integer", "minimum": 1, "maximum": 1000},
                    "sync_interval": {"type": "integer", "minimum": 60}
                }
            }
        )
    
    def initialize(self, config: Dict[str, Any], logger) -> bool:
        self.siem_type = config['siem_type']
        self.endpoint = config['endpoint']
        self.api_key = config['api_key']
        self.batch_size = config.get('batch_size', 100)
        self.sync_interval = config.get('sync_interval', 300)
        
        self.event_buffer = []
        self.connected = False
        
        return self.connect()
    
    def connect(self) -> bool:
        """Establish connection to SIEM system"""
        try:
            # Initialize SIEM-specific client
            self.client = self._create_siem_client()
            self.connected = self.client.test_connection()
            return self.connected
        except Exception as e:
            print(f"SIEM connection failed: {e}")
            return False
    
    def disconnect(self):
        """Close SIEM connection"""
        if hasattr(self, 'client'):
            self.client.close()
        self.connected = False
    
    def send_data(self, data: Dict[str, Any]) -> bool:
        """Send data to SIEM system"""
        if not self.connected:
            return False
        
        try:
            return self.client.send_event(data)
        except Exception as e:
            print(f"Failed to send data to SIEM: {e}")
            return False
    
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        """Process event and send to SIEM"""
        self.event_buffer.append(event)
        
        # Batch send events
        if len(self.event_buffer) >= self.batch_size:
            self._flush_events()
        
        # Also enrich event with SIEM data
        enriched_data = self._enrich_from_siem(event)
        
        if enriched_data:
            return [ResponseAction(
                action_id=f"siem_enrichment_{event.event_id}",
                action_type=ResponseActionType.LOG,
                priority=3,
                target=event.source,
                parameters={"enriched_data": enriched_data}
            )]
        
        return []
    
    def _create_siem_client(self):
        """Create SIEM-specific client"""
        if self.siem_type == "splunk":
            return SplunkClient(self.endpoint, self.api_key)
        elif self.siem_type == "qradar":
            return QRadarClient(self.endpoint, self.api_key)
        elif self.siem_type == "sentinel":
            return SentinelClient(self.endpoint, self.api_key)
        elif self.siem_type == "elastic":
            return ElasticClient(self.endpoint, self.api_key)
        else:
            raise ValueError(f"Unsupported SIEM type: {self.siem_type}")
    
    def _flush_events(self):
        """Send buffered events to SIEM"""
        if not self.event_buffer or not self.connected:
            return
        
        batch_data = []
        for event in self.event_buffer:
            batch_data.append(self._convert_event_to_siem_format(event))
        
        try:
            self.client.send_batch(batch_data)
            self.event_buffer.clear()
        except Exception as e:
            print(f"Failed to flush events to SIEM: {e}")
    
    def _convert_event_to_siem_format(self, event: SecurityEvent) -> Dict[str, Any]:
        """Convert SecurityEvent to SIEM-specific format"""
        return {
            'timestamp': event.timestamp.isoformat(),
            'event_id': event.event_id,
            'event_type': event.event_type.value,
            'source': event.source,
            'severity': event.severity,
            'data': event.data,
            'tags': list(event.tags),
            'metadata': event.metadata
        }
    
    def _enrich_from_siem(self, event: SecurityEvent) -> Dict[str, Any]:
        """Enrich event with data from SIEM"""
        try:
            # Query SIEM for related events or threat intelligence
            related_events = self.client.query_related_events(
                event.source, 
                event.timestamp - timedelta(hours=1),
                event.timestamp + timedelta(minutes=5)
            )
            
            return {
                'related_events_count': len(related_events),
                'related_events': related_events[:5],  # Limit to 5 most recent
                'siem_source': self.siem_type
            }
        except Exception as e:
            print(f"SIEM enrichment failed: {e}")
            return {}

# Placeholder SIEM client classes
class SplunkClient:
    def __init__(self, endpoint: str, api_key: str):
        self.endpoint = endpoint
        self.api_key = api_key
    
    def test_connection(self) -> bool:
        return True  # Placeholder
    
    def send_event(self, event_data: Dict[str, Any]) -> bool:
        return True  # Placeholder
    
    def send_batch(self, batch_data: List[Dict[str, Any]]) -> bool:
        return True  # Placeholder
    
    def query_related_events(self, source: str, start_time: datetime, end_time: datetime) -> List[Dict[str, Any]]:
        return []  # Placeholder
    
    def close(self):
        pass

class QRadarClient(SplunkClient):
    pass

class SentinelClient(SplunkClient):
    pass

class ElasticClient(SplunkClient):
    pass

# ============================================================================
# USAGE EXAMPLE AND FRAMEWORK INTEGRATION
# ============================================================================

class KKGSecurityFramework:
    """Main framework class integrating all components"""
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        
        # Initialize core components
        plugin_dirs = [Path(d) for d in config.get('plugin_directories', ['./plugins'])]
        encryption_key = config.get('encryption_key')
        
        self.plugin_manager = PluginManager(
            plugin_directories=plugin_dirs,
            encryption_key=encryption_key.encode() if encryption_key else None,
            max_concurrent_plugins=config.get('max_plugins', 50)
        )
        
        # Initialize advanced features
        self.resource_monitor = PluginResourceMonitor(self.plugin_manager)
        self.hot_reloader = PluginHotReloader(self.plugin_manager)
        self.registry = PluginRegistry()
        
        # Event processing
        self.event_queue = queue.Queue()
        self.response_queue = queue.Queue()
        self.running = False
        
    def start(self):
        """Start the security framework"""
        print("🚀 Starting KK&G Security Framework...")
        
        # Discover and load plugins
        discovered = self.plugin_manager.discover_plugins()
        print(f"📊 Discovered {len(discovered)} plugins")
        
        # Load plugins based on configuration
        plugins_to_load = self.config.get('enabled_plugins', [])
        if not plugins_to_load:
            plugins_to_load = list(discovered.keys())
        
        loaded_count = 0
        for plugin_name in plugins_to_load:
            plugin_config = self.config.get('plugin_configs', {}).get(plugin_name, {})
            if self.plugin_manager.load_plugin(plugin_name, plugin_config):
                loaded_count += 1
        
        print(f"✅ Loaded {loaded_count}/{len(plugins_to_load)} plugins")
        
        # Start monitoring
        self.resource_monitor.start_monitoring()
        if self.config.get('enable_hot_reload', False):
            self.hot_reloader.start_watching()
        
        # Start event processing
        self.running = True
        self.event_processor = threading.Thread(target=self._process_events, daemon=True)
        self.event_processor.start()
        
        print("🛡️ KK&G Security Framework is active!")
    
    def stop(self):
        """Stop the security framework"""
        print("🛑 Stopping KK&G Security Framework...")
        
        self.running = False
        
        # Stop monitoring
        self.resource_monitor.stop_monitoring()
        self.hot_reloader.stop_watching()
        
        # Unload all plugins
        for plugin_name in list(self.plugin_manager.loaded_plugins.keys()):
            self.plugin_manager.unload_plugin(plugin_name)
        
        print("✅ KK&G Security Framework stopped")
    
    def process_security_event(self, event: SecurityEvent):
        """Add event to processing queue"""
        self.event_queue.put(event)
    
    def _process_events(self):
        """Main event processing loop"""
        while self.running:
            try:
                # Get event from queue (with timeout)
                event = self.event_queue.get(timeout=1.0)
                
                # Process through plugin manager
                responses = self.plugin_manager.process_event(event)
                
                # Queue responses for execution
                for response in responses:
                    self.response_queue.put(response)
                
                self.event_queue.task_done()
                
            except queue.Empty:
                continue
            except Exception as e:
                print(f"Event processing error: {e}")
    
    def get_framework_status(self) -> Dict[str, Any]:
        """Get comprehensive framework status"""
        return {
            'version': '2.1.0',
            'running': self.running,
            'plugins': {
                'loaded': len(self.plugin_manager.loaded_plugins),
                'available': len(self.plugin_manager.discovery.discovered_plugins),
                'status': self.plugin_manager.get_plugin_status()
            },
            'queues': {
                'events_pending': self.event_queue.qsize(),
                'responses_pending': self.response_queue.qsize()
            },
            'resources': {
                'monitoring_active': self.resource_monitor.monitoring_active,
                'hot_reload_active': self.hot_reloader.watching
            }
        }

# ============================================================================
# PLUGIN DEVELOPMENT UTILITIES
# ============================================================================

class PluginTemplate:
    """Template generator for creating new plugins"""
    
    @staticmethod
    def generate_basic_plugin(plugin_name: str, 
                             plugin_type: str = "detection",
                             author: str = "KK&G DevOps") -> str:
        """Generate basic plugin template"""
        
        if plugin_type == "detection":
            base_class = "ThreatDetectionPlugin"
            capabilities = ['threat_detection', 'event_processing']
            methods = """
    def detect_threats(self, event: SecurityEvent) -> List[Dict[str, Any]]:
        \"\"\"Implement your threat detection logic here\"\"\"
        threats = []
        
        # Your detection logic here
        # Example:
        # if self._is_suspicious(event):
        #     threats.append({
        #         'id': f'threat_{event.event_id}',
        #         'type': 'custom_threat',
        #         'confidence': 0.8,
        #         'details': {}
        #     })
        
        return threats
    
    def _is_suspicious(self, event: SecurityEvent) -> bool:
        \"\"\"Helper method for threat analysis\"\"\"
        # Implement your analysis logic
        return False"""
        
        elif plugin_type == "integration":
            base_class = "IntegrationPlugin"
            capabilities = ['integration', 'reporting']
            methods = """
    def connect(self) -> bool:
        \"\"\"Establish connection to external system\"\"\"
        try:
            # Initialize your connection here
            self.connected = True
            return True
        except Exception as e:
            print(f"Connection failed: {e}")
            return False
    
    def disconnect(self):
        \"\"\"Close connection to external system\"\"\"
        # Clean up connections here
        self.connected = False
    
    def send_data(self, data: Dict[str, Any]) -> bool:
        \"\"\"Send data to external system\"\"\"
        if not self.connected:
            return False
        
        try:
            # Send data to external system
            return True
        except Exception as e:
            print(f"Send failed: {e}")
            return False"""
        
        else:  # basic event processor
            base_class = "EventProcessorPlugin"
            capabilities = ['event_processing']
            methods = """
    def process_event(self, event: SecurityEvent) -> List[ResponseAction]:
        \"\"\"Process security events\"\"\"
        actions = []
        
        # Your event processing logic here
        # Example:
        # if event.severity > 7:
        #     actions.append(ResponseAction(
        #         action_id=f'alert_{event.event_id}',
        #         action_type=ResponseActionType.ALERT,
        #         priority=event.severity,
        #         target=event.source,
        #         parameters={'message': 'High severity event detected'}
        #     ))
        
        return actions"""
        
        template = f'''#!/usr/bin/env python3
"""
{plugin_name.title().replace('_', ' ')} Plugin
Generated by KK&G Plugin Template Generator
"""

from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from kkg_security import (
    {base_class}, PluginManifest, PluginCapability,
    SecurityEvent, ResponseAction, SecurityEventType, ResponseActionType
)

# Plugin Manifest - Required for plugin discovery
PLUGIN_MANIFEST = {{
    'name': '{plugin_name}',
    'version': '1.0.0',
    'author': '{author}',
    'description': 'Auto-generated {plugin_type} plugin',
    'capabilities': {capabilities},
    'dependencies': [],
    'platform_requirements': [],
    'event_types': [],  # Specify which event types to handle
    'api_version': '1.0',
    'license_required': True,
    'config_schema': {{
        'type': 'object',
        'required': [],  # Add required config fields
        'properties': {{
            # Define your configuration schema here
            # 'threshold': {{'type': 'number', 'minimum': 0, 'maximum': 1}},
            # 'enabled': {{'type': 'boolean'}}
        }}
    }},
    'resource_limits': {{
        'max_memory_mb': 100,
        'max_cpu_percent': 10
    }}
}}

class {plugin_name.title().replace('_', '')}Plugin({base_class}):
    """
    {plugin_name.title().replace('_', ' ')} Plugin
    
    TODO: Add detailed description of what this plugin does
    """
    
    @property
    def manifest(self) -> PluginManifest:
        """Return plugin manifest"""
        return PluginManifest(
            name=PLUGIN_MANIFEST['name'],
            version=PLUGIN_MANIFEST['version'],
            author=PLUGIN_MANIFEST['author'],
            description=PLUGIN_MANIFEST['description'],
            capabilities=[PluginCapability(c) for c in PLUGIN_MANIFEST['capabilities']],
            dependencies=PLUGIN_MANIFEST['dependencies'],
            platform_requirements=PLUGIN_MANIFEST['platform_requirements'],
            event_types=[SecurityEventType(t) for t in PLUGIN_MANIFEST['event_types']],
            api_version=PLUGIN_MANIFEST['api_version'],
            license_required=PLUGIN_MANIFEST['license_required'],
            config_schema=PLUGIN_MANIFEST['config_schema'],
            resource_limits=PLUGIN_MANIFEST['resource_limits']
        )
    
    def initialize(self, config: Dict[str, Any], logger) -> bool:
        """Initialize the plugin with configuration"""
        self._logger = logger
        
        # Store configuration
        # self.threshold = config.get('threshold', 0.8)
        # self.enabled = config.get('enabled', True)
        
        # Initialize any resources, connections, etc.
        
        self._logger.info(f"{{{plugin_name}}} plugin initialized")
        return True
    
    def shutdown(self):
        """Cleanup when plugin is being unloaded"""
        super().shutdown()
        
        # Clean up resources, close connections, etc.
        
        if self._logger:
            self._logger.info(f"{{{plugin_name}}} plugin shutdown")
{methods}

# Plugin entry point - KK&G framework will automatically discover this
def create_plugin():
    """Factory function to create plugin instance"""
    return {plugin_name.title().replace('_', '')}Plugin()

if __name__ == "__main__":
    # Test code - can be used for standalone testing
    print(f"Testing {plugin_name} plugin...")
    
    plugin = create_plugin()
    
    # Create test configuration
    test_config = {{
        # Add test configuration here
    }}
    
    # Initialize plugin
    if plugin.initialize(test_config, None):
        print("✅ Plugin initialized successfully")
        
        # Create test event
        test_event = SecurityEvent(
            event_id="test_001",
            timestamp=datetime.now(),
            event_type=SecurityEventType.CUSTOM,
            source="test_source",
            data={{"test": "data"}},
            severity=5
        )
        
        # Test event processing
        if hasattr(plugin, 'process_event'):
            responses = plugin.process_event(test_event)
            print(f"Generated {{len(responses)}} responses")
        
        if hasattr(plugin, 'detect_threats'):
            threats = plugin.detect_threats(test_event)
            print(f"Detected {{len(threats)}} threats")
        
        # Cleanup
        plugin.shutdown()
        print("✅ Plugin test completed")
    else:
        print("❌ Plugin initialization failed")
'''
        
        return template
    
    @staticmethod
    def generate_plugin_tests(plugin_name: str) -> str:
        """Generate unit tests for plugin"""
        return f'''#!/usr/bin/env python3
"""
Unit tests for {plugin_name} plugin
Generated by KK&G Plugin Template Generator
"""

import unittest
from datetime import datetime
from unittest.mock import Mock, patch

from {plugin_name} import {plugin_name.title().replace('_', '')}Plugin
from kkg_security import SecurityEvent, SecurityEventType

class Test{plugin_name.title().replace('_', '')}Plugin(unittest.TestCase):
    """Test cases for {plugin_name} plugin"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.plugin = {plugin_name.title().replace('_', '')}Plugin()
        self.test_config = {{
            # Add test configuration
        }}
        
        # Mock logger
        self.mock_logger = Mock()
        
    def tearDown(self):
        """Clean up after tests"""
        if hasattr(self.plugin, 'shutdown'):
            self.plugin.shutdown()
    
    def test_plugin_initialization(self):
        """Test plugin initializes correctly"""
        result = self.plugin.initialize(self.test_config, self.mock_logger)
        self.assertTrue(result, "Plugin should initialize successfully")
        
    def test_manifest_properties(self):
        """Test plugin manifest has required properties"""
        manifest = self.plugin.manifest
        
        self.assertEqual(manifest.name, '{plugin_name}')
        self.assertTrue(manifest.version)
        self.assertTrue(manifest.author)
        self.assertTrue(manifest.description)
        self.assertIsInstance(manifest.capabilities, list)
        
    def test_configuration_validation(self):
        """Test configuration validation"""
        # Test valid configuration
        valid_config = self.test_config
        self.assertTrue(self.plugin.validate_configuration(valid_config))
        
        # Test invalid configuration
        invalid_config = {{}}  # Missing required fields
        # self.assertFalse(self.plugin.validate_configuration(invalid_config))
    
    def test_event_processing(self):
        """Test event processing functionality"""
        # Initialize plugin
        self.plugin.initialize(self.test_config, self.mock_logger)
        
        # Create test event
        test_event = SecurityEvent(
            event_id="test_001",
            timestamp=datetime.now(),
            event_type=SecurityEventType.CUSTOM,
            source="test_source",
            data={{"test": "data"}},
            severity=5
        )
        
        # Test processing
        if hasattr(self.plugin, 'process_event'):
            responses = self.plugin.process_event(test_event)
            self.assertIsInstance(responses, list)
        
        if hasattr(self.plugin, 'detect_threats'):
            threats = self.plugin.detect_threats(test_event)
            self.assertIsInstance(threats, list)
    
    def test_health_status(self):
        """Test health status reporting"""
        self.plugin.initialize(self.test_config, self.mock_logger)
        
        health = self.plugin.get_health_status()
        self.assertIsInstance(health, dict)
        self.assertIn('state', health)
        self.assertIn('metrics', health)
    
    def test_error_handling(self):
        """Test plugin handles errors gracefully"""
        # Test with invalid configuration
        invalid_config = {{"invalid": "config"}}
        
        # Should not raise exception
        try:
            self.plugin.initialize(invalid_config, self.mock_logger)
        except Exception as e:
            self.fail(f"Plugin should handle invalid config gracefully: {{e}}")

if __name__ == '__main__':
    unittest.main()
'''

class PluginValidator:
    """Validates plugin code and configurations"""
    
    def __init__(self):
        self.validation_rules = [
            self._check_manifest_present,
            self._check_required_methods,
            self._check_imports,
            self._check_security_patterns,
            self._check_resource_usage,
        ]
    
    def validate_plugin(self, plugin_path: Path) -> Dict[str, Any]:
        """Validate a plugin file"""
        validation_results = {
            'valid': True,
            'errors': [],
            'warnings': [],
            'suggestions': []
        }
        
        try:
            with open(plugin_path, 'r') as f:
                source_code = f.read()
            
            for rule in self.validation_rules:
                rule_result = rule(source_code, plugin_path)
                
                validation_results['errors'].extend(rule_result.get('errors', []))
                validation_results['warnings'].extend(rule_result.get('warnings', []))
                validation_results['suggestions'].extend(rule_result.get('suggestions', []))
                
                if rule_result.get('errors'):
                    validation_results['valid'] = False
            
        except Exception as e:
            validation_results['valid'] = False
            validation_results['errors'].append(f"Failed to read plugin file: {e}")
        
        return validation_results
    
    def _check_manifest_present(self, source_code: str, plugin_path: Path) -> Dict[str, List[str]]:
        """Check if plugin manifest is present"""
        result = {'errors': [], 'warnings': [], 'suggestions': []}
        
        if 'PLUGIN_MANIFEST' not in source_code:
            result['errors'].append("Missing PLUGIN_MANIFEST constant")
        
        return result
    
    def _check_required_methods(self, source_code: str, plugin_path: Path) -> Dict[str, List[str]]:
        """Check if required methods are implemented"""
        result = {'errors': [], 'warnings': [], 'suggestions': []}
        
        required_methods = ['initialize', 'manifest']
        
        for method in required_methods:
            if f'def {method}(' not in source_code:
                result['errors'].append(f"Missing required method: {method}")
        
        return result
    
    def _check_imports(self, source_code: str, plugin_path: Path) -> Dict[str, List[str]]:
        """Check for dangerous imports"""
        result = {'errors': [], 'warnings': [], 'suggestions': []}
        
        dangerous_imports = ['os', 'sys', 'subprocess', 'eval', 'exec']
        
        for imp in dangerous_imports:
            if f'import {imp}' in source_code or f'from {imp}' in source_code:
                result['warnings'].append(f"Potentially dangerous import: {imp}")
        
        return result
    
    def _check_security_patterns(self, source_code: str, plugin_path: Path) -> Dict[str, List[str]]:
        """Check for security anti-patterns"""
        result = {'errors': [], 'warnings': [], 'suggestions': []}
        
        security_patterns = [
            ('eval(', 'Use of eval() function'),
            ('exec(', 'Use of exec() function'),
            ('__import__(', 'Direct use of __import__'),
            ('shell=True', 'Shell command execution'),
        ]
        
        for pattern, message in security_patterns:
            if pattern in source_code:
                result['warnings'].append(f"Security concern: {message}")
        
        return result
    
    def _check_resource_usage(self, source_code: str, plugin_path: Path) -> Dict[str, List[str]]:
        """Check for resource usage patterns"""
        result = {'errors': [], 'warnings': [], 'suggestions': []}
        
        if 'while True:' in source_code and 'time.sleep(' not in source_code:
            result['warnings'].append("Infinite loop without sleep - may consume excessive CPU")
        
        if 'threading.Thread(' in source_code:
            if 'daemon=True' not in source_code:
                result['suggestions'].append("Consider using daemon threads for background tasks")
        
        return result

class PluginDebugger:
    """Debugging utilities for plugin development"""
    
    def __init__(self, plugin_manager: PluginManager):
        self.plugin_manager = plugin_manager
        self.debug_mode = False
        self.breakpoints: Dict[str, List[str]] = {}  # plugin_name -> method_names
        
    def enable_debug_mode(self, plugin_name: str = None):
        """Enable debug mode for specific plugin or all plugins"""
        self.debug_mode = True
        if plugin_name:
            print(f"🐛 Debug mode enabled for plugin: {plugin_name}")
        else:
            print("🐛 Debug mode enabled for all plugins")
    
    def disable_debug_mode(self):
        """Disable debug mode"""
        self.debug_mode = False
        print("🐛 Debug mode disabled")
    
    def set_breakpoint(self, plugin_name: str, method_name: str):
        """Set breakpoint in plugin method"""
        if plugin_name not in self.breakpoints:
            self.breakpoints[plugin_name] = []
        
        self.breakpoints[plugin_name].append(method_name)
        print(f"🔍 Breakpoint set: {plugin_name}.{method_name}")
    
    def trace_plugin_execution(self, plugin_name: str, event: SecurityEvent):
        """Trace plugin execution for debugging"""
        if not self.debug_mode:
            return
        
        plugin = self.plugin_manager.loaded_plugins.get(plugin_name)
        if not plugin:
            print(f"❌ Plugin {plugin_name} not found")
            return
        
        print(f"🔍 Tracing execution of plugin: {plugin_name}")
        print(f"   Event: {event.event_id} ({event.event_type.value})")
        print(f"   Source: {event.source}")
        print(f"   Severity: {event.severity}")
        
        try:
            start_time = datetime.now()
            responses = plugin.process_event(event)
            end_time = datetime.now()
            
            execution_time = (end_time - start_time).total_seconds() * 1000
            
            print(f"   ⏱️  Execution time: {execution_time:.2f}ms")
            print(f"   📤 Generated {len(responses)} responses")
            
            for i, response in enumerate(responses):
                print(f"      Response {i+1}: {response.action_type.value} (priority: {response.priority})")
                
        except Exception as e:
            print(f"   ❌ Exception during execution: {e}")
            import traceback
            traceback.print_exc()
    
    def inspect_plugin_state(self, plugin_name: str) -> Dict[str, Any]:
        """Inspect current plugin state"""
        plugin = self.plugin_manager.loaded_plugins.get(plugin_name)
        if not plugin:
            return {'error': f'Plugin {plugin_name} not found'}
        
        state_info = {
            'name': plugin_name,
            'state': plugin._get_state().name,
            'config': getattr(plugin, '_config', {}),
            'metrics': getattr(plugin, '_metrics', {}),
            'manifest': plugin.manifest.__dict__,
            'methods': [method for method in dir(plugin) if not method.startswith('_')]
        }
        
        # Add custom state information if available
        if hasattr(plugin, '_debug_state'):
            state_info['custom_state'] = plugin._debug_state
        
        return state_info
    
    def run_plugin_profiler(self, plugin_name: str, event: SecurityEvent, iterations: int = 100):
        """Profile plugin performance"""
        import time
        import statistics
        
        plugin = self.plugin_manager.loaded_plugins.get(plugin_name)
        if not plugin:
            print(f"❌ Plugin {plugin_name} not found")
            return
        
        print(f"📊 Profiling plugin: {plugin_name}")
        print(f"   Iterations: {iterations}")
        
        execution_times = []
        memory_usage_before = plugin._get_memory_usage()
        
        for i in range(iterations):
            start_time = time.perf_counter()
            try:
                responses = plugin.process_event(event)
            except Exception as e:
                print(f"   ❌ Error in iteration {i+1}: {e}")
                continue
            end_time = time.perf_counter()
            
            execution_times.append((end_time - start_time) * 1000)  # Convert to ms
        
        memory_usage_after = plugin._get_memory_usage()
        
        if execution_times:
            print(f"   ⏱️  Average execution time: {statistics.mean(execution_times):.2f}ms")
            print(f"   ⏱️  Median execution time: {statistics.median(execution_times):.2f}ms")
            print(f"   ⏱️  Min execution time: {min(execution_times):.2f}ms")
            print(f"   ⏱️  Max execution time: {max(execution_times):.2f}ms")
            print(f"   🧠 Memory usage change: {(memory_usage_after - memory_usage_before) / 1024:.1f}KB")

# ============================================================================
# COMPLETE USAGE EXAMPLE
# ============================================================================

def main():
    """Complete example of using the KK&G Plugin Architecture"""
    
    print("🚀 KK&G DevOps Cybersecurity Engine - Plugin Architecture Demo")
    print("=" * 70)
    
    # Configuration for the framework
    config = {
        'plugin_directories': ['./plugins', './custom_plugins'],
        'encryption_key': 'your-encryption-key-here',  # In production, use secure key management
        'max_plugins': 25,
        'enabled_plugins': [
            'network_anomaly_detector',
            'ml_threat_detector',
            'siem_integration'
        ],
        'plugin_configs': {
            'network_anomaly_detector': {
                'threshold': 0.7,
                'window_size': 50
            },
            'ml_threat_detector': {
                'model_path': './models/threat_detection_v2.pkl',
                'confidence_threshold': 0.8,
                'batch_size': 32
            },
            'siem_integration': {
                'siem_type': 'splunk',
                'endpoint': 'https://splunk.company.com:8089',
                'api_key': 'your-api-key',
                'batch_size': 100
            }
        },
        'enable_hot_reload': True
    }
    
    # Initialize the framework
    framework = KKGSecurityFramework(config)
    
    try:
        # Start the framework
        framework.start()
        
        # Show framework status
        status = framework.get_framework_status()
        print(f"📊 Framework Status:")
        print(f"   Running: {status['running']}")
        print(f"   Plugins loaded: {status['plugins']['loaded']}")
        print(f"   Plugins available: {status['plugins']['available']}")
        
        # Simulate some security events
        test_events = [
            SecurityEvent(
                event_id="net_001",
                timestamp=datetime.now(),
                event_type=SecurityEventType.NETWORK_ANOMALY,
                source="192.168.1.100",
                data={
                    "network_metrics": {
                        "bandwidth_usage": 95.2,
                        "connection_count": 1500,
                        "packet_loss": 0.05
                    }
                },
                severity=7,
                tags={"network", "anomaly"}
            ),
            SecurityEvent(
                event_id="endpoint_001",
                timestamp=datetime.now(),
                event_type=SecurityEventType.ENDPOINT_THREAT,
                source="WORKSTATION-01",
                data={
                    "process_info": {
                        "name": "suspicious_process.exe",
                        "pid": 1234,
                        "parent_pid": 5678,
                        "command_line": "powershell.exe -enc <encoded_payload>"
                    }
                },
                severity=9,
                tags={"endpoint", "malware"}
            ),
            SecurityEvent(
                event_id="user_001",
                timestamp=datetime.now(),
                event_type=SecurityEventType.USER_BEHAVIOR,
                source="john.doe@company.com",
                data={
                    "login_info": {
                        "failed_attempts": 15,
                        "source_ip": "203.0.113.10",
                        "user_agent": "curl/7.68.0",
                        "time_of_day": "03:30:00"
                    }
                },
                severity=6,
                tags={"authentication", "suspicious"}
            )
        ]
        
        print(f"\n🎯 Processing {len(test_events)} test events...")
        
        # Process events through the framework
        for event in test_events:
            framework.process_security_event(event)
            print(f"   📥 Queued event: {event.event_id}")
        
        # Give some time for processing
        import time
        time.sleep(2)
        
        # Show updated status
        updated_status = framework.get_framework_status()
        print(f"\n📈 Updated Status:")
        print(f"   Events pending: {updated_status['queues']['events_pending']}")
        print(f"   Responses pending: {updated_status['queues']['responses_pending']}")
        
        # Demonstrate plugin management features
        plugin_manager = framework.plugin_manager
        
        print(f"\n🔧 Plugin Management Demo:")
        
        # Show plugin status
        for plugin_name in plugin_manager.get_loaded_plugins():
            status = plugin_manager.get_plugin_status(plugin_name)
            print(f"   Plugin {plugin_name}: {status['state']}")
            
            # Show metrics if available
            if 'metrics' in status:
                metrics = status['metrics']
                print(f"      Events processed: {metrics.get('events_processed', 0)}")
                print(f"      Responses generated: {metrics.get('responses_generated', 0)}")
        
        # Demonstrate hot reloading (if a plugin file was modified)
        print(f"\n🔄 Hot Reload Demo (modify a plugin file to see this in action)")
        
        # Demonstrate plugin debugging
        debugger = PluginDebugger(plugin_manager)
        debugger.enable_debug_mode()
        
        # Create a test event for debugging
        debug_event = SecurityEvent(
            event_id="debug_001",
            timestamp=datetime.now(),
            event_type=SecurityEventType.CUSTOM,
            source="debug_source",
            data={"debug": True},
            severity=5
        )
        
        # Trace execution of first plugin
        loaded_plugins = plugin_manager.get_loaded_plugins()
        if loaded_plugins:
            debugger.trace_plugin_execution(loaded_plugins[0], debug_event)
        
        print(f"\n✅ Demo completed successfully!")
        print(f"💡 Check the plugin directories for generated files and logs")
        
    except KeyboardInterrupt:
        print(f"\n⚠️ Interrupted by user")
    except Exception as e:
        print(f"\n❌ Demo failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        # Clean shutdown
        framework.stop()
        print(f"\n👋 Framework shutdown complete")

if __name__ == "__main__":
    main()

"""
PLUGIN DEVELOPMENT GUIDE
========================

1. Creating a New Plugin:
   - Use PluginTemplate.generate_basic_plugin() to create template
   - Inherit from appropriate base class (SecurityPlugin, ThreatDetectionPlugin, etc.)
   - Implement required methods: manifest, initialize, process_event/detect_threats
   - Define PLUGIN_MANIFEST constant with metadata

2. Plugin Structure:
   ```
   my_plugin.py
   ├── PLUGIN_MANIFEST (dict)
   ├── MyPlugin class (inherits from base)
   │   ├── manifest property
   │   ├── initialize method
   │   ├── process_event/detect_threats method
   │   └── optional: shutdown, get_health_status
   └── create_plugin function (factory)
   ```

3. Configuration Schema:
   - Use JSON Schema format in manifest
   - Validate in plugin using validate_configuration
   - Access via self._config in plugin methods

4. Security Considerations:
   - Plugins run with full framework privileges
   - Use plugin sandbox for untrusted code
   - Validate all inputs and configurations
   - Implement resource limits in manifest
   - Avoid dangerous operations (eval, exec, shell commands)

5. Testing:
   - Use PluginTemplate.generate_plugin_tests() for test template
   - Test initialization, configuration validation, event processing
   - Use PluginDebugger for runtime debugging
   - Profile performance with run_plugin_profiler()

6. IP Protection:
   - Encrypt plugins using PluginEncryption
   - Use .kkg extension for encrypted plugins
   - Implement license validation in manifest
   - Use plugin registry for centralized management

7. Integration Patterns:
   - Event-driven architecture for real-time processing
   - Use ResponseAction for plugin outputs
   - Implement proper error handling and logging
   - Support hot reloading for development

8. Performance Optimization:
   - Set appropriate resource limits
   - Use efficient algorithms and data structures
   - Implement caching where appropriate
   - Monitor resource usage with PluginResourceMonitor

9. Deployment:
   - Package plugins with dependencies
   - Use plugin registry for discovery
   - Implement version compatibility checks
   - Support enterprise deployment models

This architecture provides enterprise-grade plugin capabilities while
maintaining security, performance, and ease of development.
"""